sudo: required
dist: trusty
language: c++
compiler: gcc
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5; fi
 - sudo apt-get install libboost-all-dev
script:
 - |
   mkdir build
   cd build
   cmake ..
   make -j
