version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/quant
    steps:

      - run:
          name: Download necessary files
          command: |
            apt-get update
            apt-get -y install git cmake g++ libboost-all-dev

      - checkout

      - run:
          name: Build the project
          command: |
              mkdir build
              cd build
              cmake ..
              make -j4

